export const PROFILE = {
  name: "Sheikh Siam",
  role: "Full-Stack Developer",
  tagline: "Building scalable web applications with modern technologies.",
  email: "siamtechofficial1597@gmail.com",
  location: "Bangladesh",
  github: "https://github.com/Siam24857",
  linkedin: "https://www.linkedin.com/in/sheikh-siam/",
  resume: "https://drive.google.com/file/d/1_jF1S2jq8ExXsPVmfr4UX_W6zDUCFnZx/view?usp=sharing",
};

export const SKILLS_DATA = {
  categories: [
    {
      id: "frontend",
      title: "Frontend Development",
      accent: "#ff6b6b",
      skills: [
        { name: "HTML5", icon: "SiHtml5", color: "#E34F26", level: 96, xp: 8500, levelNum: 5 },
        { name: "CSS3", icon: "SiCss3", color: "#1572B6", level: 95, xp: 8300, levelNum: 5 },
        { name: "JavaScript", icon: "SiJavascript", color: "#F7DF1E", level: 95, xp: 8100, levelNum: 5 },
        { name: "TypeScript", icon: "SiTypescript", color: "#3178C6", level: 92, xp: 7800, levelNum: 4 },
        { name: "React.js", icon: "SiReact", color: "#61DAFB", level: 96, xp: 8500, levelNum: 5 },
        { name: "Next.js 14", icon: "SiNextdotjs", color: "#FFFFFF", level: 94, xp: 8200, levelNum: 5 },
        { name: "JSX", icon: "SiReact", color: "#61DAFB", level: 94, xp: 8100, levelNum: 5 },
        { name: "Tailwind CSS", icon: "SiTailwindcss", color: "#06B6D4", level: 96, xp: 8400, levelNum: 5 },
        { name: "Bootstrap", icon: "SiBootstrap", color: "#7952B3", level: 88, xp: 7000, levelNum: 4 },
        { name: "Responsive Web Design", icon: "MdDevices", color: "#10B981", level: 94, xp: 7900, levelNum: 4 },
        { name: "REST API Integration", icon: "MdApi", color: "#10B981", level: 92, xp: 7600, levelNum: 4 },
        { name: "Modern UI Development", icon: "MdBrush", color: "#ff6b6b", level: 90, xp: 7300, levelNum: 4 },
      ],
    },
    {
      id: "backend",
      title: "Backend Development",
      accent: "#f5a623",
      skills: [
        { name: "Node.js", icon: "SiNodedotjs", color: "#68A063", level: 90, xp: 7200, levelNum: 4 },
        { name: "Express.js", icon: "SiExpress", color: "#FFFFFF", level: 88, xp: 6900, levelNum: 4 },
        { name: "TypeScript", icon: "SiTypescript", color: "#3178C6", level: 92, xp: 7800, levelNum: 4 },
        { name: "REST APIs", icon: "MdApi", color: "#10B981", level: 92, xp: 7500, levelNum: 4 },
        { name: "JWT Authentication", icon: "MdLock", color: "#ff6b6b", level: 90, xp: 7200, levelNum: 4 },
        { name: "Role-Based Authentication", icon: "MdLock", color: "#f5a623", level: 88, xp: 6900, levelNum: 4 },
        { name: "Server-Side Development", icon: "MdStorage", color: "#7c3aed", level: 86, xp: 6500, levelNum: 4 },
        { name: "API Development", icon: "MdApi", color: "#10B981", level: 92, xp: 7500, levelNum: 4 },
      ],
    },
    {
      id: "database",
      title: "Database & ORM",
      accent: "#7c3aed",
      skills: [
        { name: "MongoDB", icon: "SiMongodb", color: "#68A063", level: 90, xp: 7200, levelNum: 4 },
        { name: "MongoDB Atlas", icon: "SiMongodb", color: "#68A063", level: 88, xp: 6900, levelNum: 4 },
        { name: "PostgreSQL", icon: "SiPostgresql", color: "#336791", level: 85, xp: 6500, levelNum: 3 },
        { name: "Prisma ORM", icon: "SiPrisma", color: "#2D3748", level: 88, xp: 6700, levelNum: 4 },
        { name: "CRUD Operations", icon: "MdSwapVert", color: "#10B981", level: 92, xp: 7500, levelNum: 4 },
        { name: "Aggregation Pipeline", icon: "SiMongodb", color: "#68A063", level: 85, xp: 6500, levelNum: 3 },
        { name: "Database Design", icon: "MdStorage", color: "#7c3aed", level: 86, xp: 6600, levelNum: 4 },
        { name: "Database Integration", icon: "MdStorage", color: "#7c3aed", level: 88, xp: 6800, levelNum: 4 },
        { name: "MongoDB Query Operators", icon: "SiMongodb", color: "#68A063", level: 88, xp: 6900, levelNum: 4 },
      ],
    },
    {
      id: "auth",
      title: "Authentication & Security",
      accent: "#06b6d4",
      skills: [
        { name: "JWT", icon: "MdLock", color: "#ff6b6b", level: 90, xp: 7200, levelNum: 4 },
        { name: "Better Auth", icon: "MdLock", color: "#f5a623", level: 85, xp: 6500, levelNum: 3 },
        { name: "Authentication & Authorization", icon: "MdLock", color: "#ff6b6b", level: 90, xp: 7200, levelNum: 4 },
        { name: "Protected Routes", icon: "MdLock", color: "#f5a623", level: 88, xp: 6900, levelNum: 4 },
        { name: "Role-Based Access Control", icon: "MdLock", color: "#06b6d4", level: 88, xp: 6900, levelNum: 4 },
      ],
    },
    {
      id: "apis",
      title: "APIs & Integrations",
      accent: "#10B981",
      skills: [
        { name: "REST APIs", icon: "MdApi", color: "#10B981", level: 92, xp: 7500, levelNum: 4 },
        { name: "Google APIs", icon: "SiGoogle", color: "#4285F4", level: 85, xp: 6500, levelNum: 3 },
        { name: "API Integration", icon: "MdApi", color: "#10B981", level: 90, xp: 7200, levelNum: 4 },
        { name: "Third-Party API Integration", icon: "MdApi", color: "#10B981", level: 88, xp: 6900, levelNum: 4 },
        { name: "Authentication APIs", icon: "MdLock", color: "#ff6b6b", level: 90, xp: 7200, levelNum: 4 },
      ],
    },
    {
      id: "tools",
      title: "Tools & Platforms",
      accent: "#7c3aed",
      skills: [
        { name: "Git", icon: "SiGit", color: "#F05032", level: 94, xp: 8000, levelNum: 5 },
        { name: "GitHub", icon: "SiGithub", color: "#FFFFFF", level: 94, xp: 8000, levelNum: 5 },
        { name: "VS Code", icon: "VscVscode", color: "#007ACC", level: 96, xp: 8400, levelNum: 5 },
        { name: "Postman", icon: "SiPostman", color: "#FF6C37", level: 90, xp: 7200, levelNum: 4 },
        { name: "Figma", icon: "SiFigma", color: "#F24E1E", level: 82, xp: 6200, levelNum: 3 },
        { name: "Vercel", icon: "SiVercel", color: "#FFFFFF", level: 92, xp: 7600, levelNum: 4 },
        { name: "Netlify", icon: "SiNetlify", color: "#00C7B7", level: 88, xp: 6800, levelNum: 4 },
        { name: "GitHub Pages", icon: "SiGithub", color: "#FFFFFF", level: 86, xp: 6500, levelNum: 3 },
      ],
    },
    {
      id: "ui-animation",
      title: "UI / Animation",
      accent: "#f5a623",
      skills: [
        { name: "HeroUI", icon: "SiReact", color: "#ff6b6b", level: 82, xp: 6200, levelNum: 3 },
        { name: "DaisyUI", icon: "SiReact", color: "#f5a623", level: 80, xp: 6000, levelNum: 3 },
        { name: "Recharts", icon: "SiRecharts", color: "#06B6D4", level: 85, xp: 6500, levelNum: 3 },
        { name: "GSAP", icon: "SiGreensock", color: "#88CE02", level: 90, xp: 7200, levelNum: 4 },
        { name: "Framer Motion", icon: "MdAnimation", color: "#ff6b6b", level: 92, xp: 7600, levelNum: 4 },
        { name: "Lenis", icon: "MdAnimation", color: "#f5a623", level: 85, xp: 6500, levelNum: 3 },
        { name: "CSS Animations", icon: "MdAnimation", color: "#10B981", level: 94, xp: 7900, levelNum: 4 },
        { name: "Responsive UI/UX", icon: "MdDevices", color: "#7c3aed", level: 92, xp: 7600, levelNum: 4 },
      ],
    },
    {
      id: "fullstack",
      title: "Full-Stack Development",
      accent: "#ff6b6b",
      skills: [
        { name: "MERN Stack", icon: "SiMongodb", color: "#68A063", level: 92, xp: 7500, levelNum: 4 },
        { name: "Next.js Full-Stack", icon: "SiNextdotjs", color: "#FFFFFF", level: 94, xp: 7900, levelNum: 4 },
        { name: "Full-Stack Web Development", icon: "SiReact", color: "#61DAFB", level: 94, xp: 7900, levelNum: 4 },
        { name: "Frontend Development", icon: "SiReact", color: "#61DAFB", level: 96, xp: 8500, levelNum: 5 },
        { name: "Backend Development", icon: "SiNodedotjs", color: "#68A063", level: 90, xp: 7200, levelNum: 4 },
        { name: "API Development", icon: "MdApi", color: "#10B981", level: 92, xp: 7500, levelNum: 4 },
        { name: "Database Integration", icon: "MdStorage", color: "#7c3aed", level: 90, xp: 7200, levelNum: 4 },
        { name: "Deployment", icon: "SiVercel", color: "#FFFFFF", level: 92, xp: 7600, levelNum: 4 },
        { name: "Version Control", icon: "SiGit", color: "#F05032", level: 94, xp: 8000, levelNum: 5 },
        { name: "Debugging & Troubleshooting", icon: "MdBugReport", color: "#ff6b6b", level: 90, xp: 7200, levelNum: 4 },
      ],
    },
    {
      id: "ai",
      title: "AI / Modern Development",
      accent: "#06b6d4",
      skills: [
        { name: "AI-Assisted Development", icon: "MdAutoAwesome", color: "#ff6b6b", level: 88, xp: 6800, levelNum: 4 },
        { name: "Front-End AI Engineering", icon: "MdAutoAwesome", color: "#f5a623", level: 86, xp: 6600, levelNum: 4 },
        { name: "AI Tools & LLMs", icon: "MdAutoAwesome", color: "#06b6d4", level: 88, xp: 6800, levelNum: 4 },
        { name: "Ollama", icon: "SiReact", color: "#10B981", level: 82, xp: 6200, levelNum: 3 },
        { name: "OpenAI API", icon: "SiReact", color: "#10B981", level: 85, xp: 6500, levelNum: 3 },
        { name: "Gemini API", icon: "SiGoogle", color: "#4285F4", level: 85, xp: 6500, levelNum: 3 },
        { name: "Claude API", icon: "SiReact", color: "#f5a623", level: 82, xp: 6200, levelNum: 3 },
        { name: "Google API Integration", icon: "SiGoogle", color: "#4285F4", level: 85, xp: 6500, levelNum: 3 },
      ],
    },
  ],
};

export const PROJECTS = [
  {
    id: 1,
    title: "AI Applications",
    image: "https://www.shutterstock.com/image-vector/web-banner-robot-hand-holding-260nw-2470763617.jpg",
    category: "AI",
    tags: ["Next.js", "React", "TypeScript", "Gemini API", "MongoDB", "Node.js", "Express.js"],
    description:
      "An AI-powered assistant frontend providing intelligent real-time chat, context-aware visual responses, Gemini API integration, dynamic streaming animations, and a futuristic cyberpunk UI.",
    github: "https://github.com/Siam24857/AI-agent-cleint.git",
    link: "https://ai-agent-cleint.vercel.app",
    featured: true,
  },
  {
    id: 2,
    title: "ERP System",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSESACNU3JMrbhmBkHxaIw5FMVjOhpNEUOqgzGPClW5EA&s=10",
    category: "Full Stack",
    tags: ["Next.js", "React", "TypeScript", "Node.js"],
    description:
      "Enterprise Resource Planning system with inventory management, order processing, financial reporting, and multi-role dashboards.",
    github: "https://github.com/Siam24857/Cloudflare-client.git",
    link: "https://cloudflare-client-omega.vercel.app",
    featured: false,
  },
  {
    id: 3,
    title: "Developer Tools",
    image: "https://d1qwl4ymp6qhug.cloudfront.net/Images%20for%20blog/Online%20Publishing%20Platforms.jpg",
    category: "Frontend",
    tags: [
      "JavaScript",
      "Next.js",
      "Tailwind CSS",
      "Vite",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Vercel",
    ],
    description:
      "A suite of developer utilities including code formatters, API testers, color palette generators, and snippet managers.",
    github: "https://github.com/Siam24857/Fab-E-book-platform.git",
    link: "https://fab-e-book-platform.vercel.app",
    featured: false,
  },
  {
    id: 4,
    title: "Online MarketPlace",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDWkm9MzIfeKOarZFOQj4vMWEMnO8ZpLIBzhXZMzmAh1c8ea40nje_GLys&s=10",
    category: "Full Stack",
    tags: ["React", "TypeScript", "Node.js", "Express"],
    description:
      "Production-ready full-stack applications with authentication, payment integration, admin panels, and real-time notifications.",
    github: "https://github.com/Siam24857/Marketplace-client.git",
    link: "https://marketplace-client-one.vercel.app",
    featured: false,
  },
];

export const TIMELINE = [
  {
    period: "2024 · Start",
    title: "The Beginning",
    desc: "Started with HTML, CSS, and JavaScript. Built my first static websites and fell in love with bringing designs to life in the browser.",
    tag: "Foundations",
  },
  {
    period: "2024 · Growth",
    title: "Frontend Specialization",
    desc: "Mastered responsive design and began shipping real interactive projects with React.js and Next.js.",
    tag: "React · Next.js",
  },
  {
    period: "2025 · Building",
    title: "Full-Stack Expansion",
    desc: "Expanded into backend with Node.js and Express.js. Built RESTful APIs, integrated databases, and deployed full-stack applications.",
    tag: "Node.js · Express",
  },
  {
    period: "2026 · Today",
    title: "Crafting Scalable Systems",
    desc: "Building production-grade full-stack applications with modern tooling, cloud deployment, and continuous integration.",
    tag: "Full-Stack Engineering",
  },
];

export const SOCIALS = [
  { label: "Email", value: "siamtechofficial1597@gmail.com", href: "mailto:siamtechofficial1597@gmail.com", icon: "Mail" },
  { label: "GitHub", value: "@Siam24857", href: "https://github.com/Siam24857", icon: "Github" },
  { label: "LinkedIn", value: "in/sheikh-siam", href: "https://www.linkedin.com/in/sheikh-siam/", icon: "Linkedin" },
  { label: "Twitter", value: "@sheikhsiam", href: "https://twitter.com/sheikhsiam", icon: "Twitter" },
  { label: "Dribbble", value: "@sheikhsiam", href: "https://dribbble.com/sheikhsiam", icon: "Dribbble" },
];
